// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantages: dynamic(() => import("./Advantages")),
  alternate_text: dynamic(() => import("./AlternateText")),
  facts: dynamic(() => import("./Facts")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  steps: dynamic(() => import("./HowDoesItWork")),
};
